# Site settings
title:       Design Your Society
email:       designyoursociety@gmail.com
author:      Design your society
description: "Lets build it together"
baseurl:     ""
url:         "http://designyoursociety.com"
date_format: "%b %-d, %Y"
# Owner/author information
owner:
name:           Design Your Society
avatar:         dys.jpg
email:          designyoursociety@gmail.com
twitter_username:
github_username:
github_username:
# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Cool Option 1
    link: www.myawesomelink.com
  option2:
    name: Cool Option 2
    link: www.myawesomelink.com
  option3:
    name: Cool Option 3
    link: www.myawesomelink.com

# Build settings
markdown: kramdown

# Optional features
animated:           true
show_related_posts: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: designyoursociety
